server:
  port: ${SERVER_PORT}
 
logging:
  level:
    org:
      springframework: info
      
spring:
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fomat_sql: true
    hibernate:
      ddl-auto: update
    show_sq: true
    